# Generated by Django 5.1.2 on 2024-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dress_photo_hover'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='carted_by_users', to='products.dress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(related_name='liked_by_users', to='products.dress'),
        ),
    ]
