# Generated by Django 5.1.2 on 2024-11-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
