# Generated by Django 5.1.2 on 2024-11-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoney', '0002_balancechange_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancechange',
            old_name='date_joined',
            new_name='date',
        ),
    ]
