# Generated by Django 5.1.2 on 2024-11-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoney', '0005_alter_balancechange_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='purchase',
            field=models.TextField(),
        ),
    ]
