# Generated by Django 5.1.2 on 2024-11-05 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order'),
        ('yoomoney', '0006_alter_balancechange_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancechange',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.order'),
            preserve_default=False,
        ),
    ]
