# Generated by Django 5.1.2 on 2024-11-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoney', '0007_balancechange_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='amount_value',
            field=models.IntegerField(),
        ),
    ]
