# Generated by Django 5.1.2 on 2024-10-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dress_photo_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='photo_hover',
            field=models.ImageField(upload_to='products_images'),
        ),
    ]
