# Generated by Django 5.1.2 on 2024-11-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_dress_photo_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
